name: "Roehn-Automacao"
version: "1.0.0"
slug: "roehn_automacao"
description: "Application for managing Roehn automation projects"
arch:
  - "aarch64"
  - "amd64"
  - "armhf"
  - "armv7"
  - "i386"
startup: "application"  # Must be "services" for s6
ports:
  "5000/tcp": 5000
ingress: false
watchdog: "http://[HOST]:5000/api/session"
webui: "http://[HOST]:5000"
panel_icon: "mdi:robot"
panel_title: "Roehn-Automacao"
apparmor: false
uart: false
gpio: false
usb: false
hassio_api: false
hassio_role: "default"
homeassistant_api: false
host_network: false
tmpfs: false
discovery: []
map:
  - "ssl:rw"
  - "share:rw"
  - "addons:rw"  # Add this line
options:
  log_level: "info"
schema:
  log_level: "list(trace|debug|info|notice|warning|error|fatal)?"
# NO image field - Home Assistant will build it